name: Tests

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CI: true
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      # Jest Unit Tests
      - name: Run Jest Unit Tests
        run: npx jest --ci --coverage

      - name: Upload Jest Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-coverage-report
          path: coverage/
          retention-days: 30

      # Conditional steps for Playwright E2E Tests on 'main' branch only
      - name: Install Playwright Browsers
        if: github.ref == 'refs/heads/main'
        run: npx playwright install --with-deps

      - name: Build Next.js application
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Start server
        if: github.ref == 'refs/heads/main'
        run: npm run start &

      - name: Wait for server to be ready
        if: github.ref == 'refs/heads/main'
        run: |
          timeout 30 bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 1; done'

      - name: Run Playwright Tests
        if: github.ref == 'refs/heads/main'
        run: npx playwright test

      - name: Upload Playwright Report
        if: ${{ github.ref == 'refs/heads/main' && always() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
